In [1]:
# Import dependencies
import pandas as pd
import gmaps
import gmaps.datasets
import requests
# Import the API key.
from config import g_key
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [7]:
# Get data from csv file
hotel_info_df = pd.read_csv("weather_data/WeatherPy_vacation.csv")
hotel_info_df.set_index("City_ID")

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
City_ID,,,,,,,
1,Iwanai,JP,40.10,scattered clouds,42.97,140.51,いわない高原ホテル
2,Arvika,SE,28.00,broken clouds,59.65,12.59,Clarion Collection Hotel Bristol
3,Hamilton,CA,39.20,broken clouds,43.26,-79.87,Sheraton Hamilton Hotel
6,Puerto Ayora,EC,69.01,few clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
10,Port Hardy,CA,48.20,light intensity drizzle,50.70,-127.42,Airport Inn
...,...,...,...,...,...,...,...
560,Luchegorsk,RU,36.10,scattered clouds,46.44,134.30,Ulunga
561,San Antonio,CL,56.28,clear sky,-33.58,-71.61,Hotel Mellati
562,Knyaze-Volkonskoye,RU,35.60,clear sky,48.46,135.46,Obshchezhitiye
564,Poum,MK,48.20,light rain,41.28,20.71,Dolno Tateši
565,Yarmouth,CA,41.00,broken clouds,43.84,-66.12,Comfort Inn

In [10]:
# Create DataFrames for each city in the itinerary.
bermeo_df = hotel_info_df.loc[hotel_info_df["City"] == 'Bermeo']
bereda_df = hotel_info_df.loc[hotel_info_df["City"] == 'Bereda']
azuaga_df = hotel_info_df.loc[hotel_info_df["City"] == 'Azuaga']
lagoa_df = hotel_info_df.loc[hotel_info_df["City"] == 'Lagoa']

In [11]:
# Combine the cities into the vacation DataFrame
vacation_cities_df = pd.concat([bermeo_df, bereda_df, azuaga_df, lagoa_df])
vacation_cities_df.set_index("City_ID")

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
City_ID,,,,,,,
371,Bermeo,ES,45.00,thunderstorm with light rain,43.42,-2.72,Eco-Hotel Mundaka
477,Bereda,ES,55.00,scattered clouds,43.27,-7.54,Pazo de Verdes
540,Azuaga,ES,44.01,overcast clouds,38.26,-5.68,Casa Rural La Hoya
82,Lagoa,PT,57.20,overcast clouds,37.14,-8.45,Agua Hotels Vale Da Lapa Lagoa

In [20]:
# Add info boxes to markers.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
lodging_info = [info_box_template.format(**row) for index, row in vacation_cities_df.iterrows()]

In [38]:
# Add a marker layer map for the vacation spots.
locations = vacation_cities_df[["Lat", "Lng"]]
max_temp = vacation_cities_df["Max Temp"]
fig = gmaps.figure(center=(40.4, 3), zoom_level=5)
marker_layer = gmaps.marker_layer(locations, info_box_content=lodging_info)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [52]:
# Latitude-longitude pairs of vacation cities
bermeo = (locations.iloc[0]["Lat"], locations.iloc[0]["Lng"])
bereda = (locations.iloc[1]["Lat"], locations.iloc[1]["Lng"])
azuaga = (locations.iloc[2]["Lat"], locations.iloc[2]["Lng"])
lagoa = (locations.iloc[3]["Lat"], locations.iloc[3]["Lng"])
# Add directions layer of the vacation cities
fig = gmaps.figure()
bermeo2lagoa = gmaps.directions_layer(bermeo, lagoa, waypoints=[bereda, azuaga], travel_mode='DRIVING')
fig.add_layer(bermeo2lagoa)
# Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))